# -*- coding: utf-8 -*-
"""task skill(naranjana)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqJW-2-F4x6Q0evDQfN-NJMxIjxU-2bo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn  as sns

df = pd.read_csv('/content/healthcare_dataset.csv')
df

print("\nDataset Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

df['Medical_Code'].isnull()

df['Standardized_Medical_Code'] = df['Medical_Code'].str.replace('ICD-10-', '')
print(df[['Medical_Code', 'Standardized_Medical_Code']].head())

df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], format='%d-%m-%Y')
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'], format='%d-%m-%Y')

df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']
).dt.days
print(df[['Admission_Date', 'Discharge_Date', 'Hospital_Stay_Days']].head())

print("Billing Amount:")
print(df['Billing_Amount'].describe())

print("Hospital Stay Days:")
print(df['Hospital_Stay_Days'].describe())

print("\nAverage Hospital Stay:")
print(df['Hospital_Stay_Days'].mean())

print(df['Medical_Code'].value_counts())